import { EmptyState } from '../components/EmptyState'

/**
 * Optimiser — CP-SAT berth and crane assignment proposals.
 *
 * The full optimizer experience is on the Operations Plan page.
 * This page provides context and directs users there.
 *
 * Endpoint: POST /api/v1/operations-plan
 */
export default function OptimizerPage() {
  return (
    <div>
      <h1 className="text-xl font-semibold text-slate-100 mb-1">Optimiser</h1>
      <p className="text-slate-400 text-sm mb-4">
        Joint berth and crane assignment proposals generated by the OR-Tools CP-SAT solver.
      </p>
      <div className="mb-6 rounded border border-teal-700/40 bg-teal-900/10 px-4 py-3 text-teal-300 text-sm">
        <strong>Note:</strong> The full optimizer experience is on the{' '}
        <a
          href="/operations-plan"
          className="underline hover:text-teal-200 transition-colors"
        >
          Operations Plan
        </a>{' '}
        page — generate a 72-hour plan, review berth assignments, and approve before going live.
      </div>
      <div className="text-slate-500 text-xs space-y-1 mb-6">
        <p>
          <strong className="text-slate-400">POST /api/v1/operations-plan</strong> — run CP-SAT optimizer
        </p>
        <p>
          <strong className="text-slate-400">POST /api/v1/operations-plan/{'{plan_id}'}/approve</strong> — human approval gate
        </p>
        <p className="text-slate-600">
          Solver: Google OR-Tools CP-SAT · Synthetic data (seed=2026) ·
          Human approval required before any operational use
        </p>
      </div>
      <EmptyState
        title="Go to Operations Plan"
        description="Use the Operations Plan page to generate and approve a 72-hour berth and crane assignment plan via POST /api/v1/operations-plan."
      />
    </div>
  )
}
