import { EmptyState } from '../components/EmptyState'

/** Optimiser — CP-SAT berth and crane assignment proposals. */
export default function OptimizerPage() {
  return (
    <div>
      <h1 className="text-xl font-semibold text-slate-100 mb-1">Optimiser</h1>
      <p className="text-slate-400 text-sm mb-8">
        Joint berth and crane assignment proposals generated by the OR-Tools CP-SAT solver.
      </p>
      <EmptyState
        title="No optimisation results"
        description="Run POST /api/v1/plans/optimise to generate an optimised berth and crane assignment plan."
      />
    </div>
  )
}
